# FROM php:8.1-cli

# # Install ONLY what composer absolutely needs
# RUN apt-get update && apt-get install -y \
#     unzip \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*


FROM php:8.1-fpm-alpine
RUN apk update && apk add --no-cache \
    unzip \
    bash
# NO PHP EXTENSIONS - composer doesn't need them to run

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www