services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: programwithgio-app
    restart: always
    working_dir: /var/www/
    depends_on:
      composer:
        condition: service_completed_successfully
    volumes:
      - ../:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    container_name: programwithgio-composer
    # Removed 'init: true' to fix the Tini/Zombie warning
    volumes:
      - ../:/var/www
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www
    environment:
      - COMPOSER_PROCESS_TIMEOUT=600
    restart: "no"
    # This ONLY runs when you do 'docker compose up'
    command: ["/bin/bash", "/var/www/scripts/composer/main-composer.sh"]

  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: programwithgio-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306